<?php

return new class
{
    public function definition(): array { return ['report' => 'COMPANY_OCCUPANCY_DETAIL_REFERENCE', 'name' => 'Báo cáo chi tiết công suất công ty', 'page_size' => 'A4', 'page_orientation' => 'landscape', 'margin_top' => 6, 'margin_right' => 4, 'margin_bottom' => 6, 'margin_left' => 4, 'version' => '1.0', 'content_json' => $this->blocks(), 'content_html' => $this->html(), 'css' => $this->css()]; }
    private function fields(): array { return ['BookingCode','ReferenceCode','CompanyName','GuestName','MarketSegment','SourceCode','BookingDate','ArrivalDate','DepartureDate','NoOfNight','NoOfRoom','RoomNight','GuestNight','AverageRate','AverageRateOriginal','RoomRevenue','FbRevenue','OtherRevenue','TotalRevenue','RoomType','Nationality']; }
    private function labels(): array { return ['Mã ĐK','Mã tham chiếu','Tên công ty','Tên khách','Thị trường','Nguồn khách','Ngày tạo','Ngày đến','Ngày đi','Đêm','Phòng','Đêm phòng','Đêm khách','Giá phòng TB','Giá phòng TB không FOC','Doanh thu phòng','Doanh thu F&B','Doanh thu khác','Doanh thu','Loại phòng','Quốc tịch']; }
    private function blocks(): array { return ['header' => [['id' => 'header', 'type' => 'text', 'content' => 'BÁO CÁO CHI TIẾT CÔNG SUẤT CÔNG TY']], 'detail' => [['id' => 'table', 'type' => 'table', 'dataSource' => 'rows', 'tableType' => 'dynamic']], 'footer' => []]; }
    public function html(): string { $h=''; foreach($this->labels() as $label){$h.='<th>'.$label.'</th>';} $c=''; foreach($this->fields() as $f){$c.='<td>{{row.'.$f.($this->isNumber($f)?'|number':''). '}}</td>';} return '<div class="report-header"><div>{{hotel.logo}}</div><div class="hotel-information">Địa chỉ: {{hotel.address}}<br>Người dùng: {{report.generated_by}}<br>Ngày: {{report.generated_at}}</div></div><h1>BÁO CÁO CHI TIẾT CÔNG SUẤT CÔNG TY</h1><p class="period">Ngày: {{parameters.p_from_date}} ~ {{parameters.p_to_date}}</p><table><thead><tr>'.$h.'</tr></thead><tbody><tr class="pms-detail-row" data-source="rows">'.$c.'</tr><tr class="total"><td colspan="9">Tổng: {{aggregate.rows.count}}</td><td>{{aggregate.rows.sum.NoOfNight|number}}</td><td>{{aggregate.rows.sum.NoOfRoom|number}}</td><td>{{aggregate.rows.sum.RoomNight|number}}</td><td>{{aggregate.rows.sum.GuestNight|number}}</td><td colspan="2"></td><td>{{aggregate.rows.sum.RoomRevenue|number}}</td><td>{{aggregate.rows.sum.FbRevenue|number}}</td><td>{{aggregate.rows.sum.OtherRevenue|number}}</td><td>{{aggregate.rows.sum.TotalRevenue|number}}</td><td colspan="2"></td></tr></tbody></table>'; }
    private function isNumber(string $field): bool { return in_array($field, ['NoOfNight','NoOfRoom','RoomNight','GuestNight','AverageRate','AverageRateOriginal','RoomRevenue','FbRevenue','OtherRevenue','TotalRevenue'], true); }
    public function css(): string { return '.report-header{display:flex;justify-content:space-between;min-height:50px}.hotel-information{text-align:right;font-size:9px;line-height:1.5}h1{text-align:center;font-size:16px;margin:8px 0 3px}p.period{text-align:center;font-style:italic;font-size:9px}table{width:100%;border-collapse:collapse;font-size:6.7px}th,td{border:1px solid #aeb5c0;padding:2px 1px}th{background:#d9deea;text-align:center}.total td{background:#d9deea;font-weight:bold}'; }
};
