<?php

return new class
{
    public function definition(): array { return ['report' => 'SALESPERSON_REVENUE_DETAIL_REFERENCE', 'name' => 'Báo cáo chi tiết doanh thu theo người bán', 'page_size' => 'A4', 'page_orientation' => 'landscape', 'margin_top' => 6, 'margin_right' => 4, 'margin_bottom' => 6, 'margin_left' => 4, 'version' => '1.0', 'content_json' => $this->blocks(), 'content_html' => $this->html(), 'css' => $this->css()]; }
    private function fields(): array { return ['BookingCode','BookingName','ArrivalDate','DepartureDate','RoomNights','FocRoomNights','GuestQty','CompanyName','MarketSegment','RoomRevenue','FbRevenue','OtherRevenue','TotalRevenue','SalesPersonName']; }
    private function labels(): array { return ['Mã ĐK','Tên Đăng Ký','Ngày Đến','Ngày Đi','Đêm phòng','FOC','SL khách','Công Ty','Thị trường','Doanh thu phòng','Doanh thu F&B','Doanh thu khác','Tổng Doanh Thu','Người Bán']; }
    private function blocks(): array { return ['header' => [['id' => 'header', 'type' => 'text', 'content' => 'BÁO CÁO CHI TIẾT DOANH THU THEO NGƯỜI BÁN']], 'detail' => [['id' => 'table', 'type' => 'table', 'dataSource' => 'rows', 'tableType' => 'dynamic']], 'footer' => []]; }
    public function html(): string { $h=''; foreach($this->labels() as $label){$h.='<th>'.$label.'</th>';} $c=''; foreach($this->fields() as $f){$c.='<td>{{row.'.$f.(in_array($f,['RoomNights','FocRoomNights','GuestQty','RoomRevenue','FbRevenue','OtherRevenue','TotalRevenue'],true)?'|number':''). '}}</td>'; } return '<div class="report-header"><div>{{hotel.logo}}</div><div class="hotel-information">Địa chỉ: {{hotel.address}}<br>Người dùng: {{report.generated_by}}<br>Ngày: {{report.generated_at}}</div></div><h1>BÁO CÁO CHI TIẾT DOANH THU THEO NGƯỜI BÁN</h1><p class="period">Ngày: {{parameters.p_from_date}} ~ {{parameters.p_to_date}}</p><table><thead><tr>'.$h.'</tr></thead><tbody><tr class="pms-detail-row" data-source="rows">'.$c.'</tr><tr class="total"><td colspan="9">Tổng: {{aggregate.rows.count}}</td><td>{{aggregate.rows.sum.RoomRevenue|number}}</td><td>{{aggregate.rows.sum.FbRevenue|number}}</td><td>{{aggregate.rows.sum.OtherRevenue|number}}</td><td>{{aggregate.rows.sum.TotalRevenue|number}}</td><td></td></tr></tbody></table>'; }
    public function css(): string { return '.report-header{display:flex;justify-content:space-between;min-height:50px}.hotel-information{text-align:right;font-size:9px;line-height:1.5}h1{text-align:center;font-size:16px;margin:8px 0 3px}p.period{text-align:center;font-style:italic;font-size:9px}table{width:100%;border-collapse:collapse;font-size:7.5px}th,td{border:1px solid #aeb5c0;padding:2px 1px}th{background:#d9deea;text-align:center}.total td{background:#d9deea;font-weight:bold}'; }
};
