<?php

return new class
{
    public function definition(): array { return ['report' => 'SALESPERSON_REVENUE_SUMMARY_REFERENCE', 'name' => 'Báo cáo tổng hợp doanh thu theo người bán', 'page_size' => 'A4', 'page_orientation' => 'landscape', 'margin_top' => 6, 'margin_right' => 4, 'margin_bottom' => 6, 'margin_left' => 4, 'version' => '1.0', 'content_json' => $this->blocks(), 'content_html' => $this->html(), 'css' => $this->css()]; }
    private function fields(): array { return ['SalesPersonCode','SalesPersonName','OccupancyRate','RoomNights','GuestQty','ActualADR','RackADR','RoomRevenue','FbRevenue','OtherRevenue','TotalRevenue']; }
    private function labels(): array { return ['Mã NV','Người Bán','Công suất','Đêm phòng','SL khách','Giá phòng TB','Giá phòng TB không FOC','Doanh thu phòng','Doanh thu F&B','Doanh thu khác','Doanh Thu']; }
    private function blocks(): array { return ['header' => [['id' => 'header', 'type' => 'text', 'content' => 'BÁO CÁO DOANH THU THEO NGƯỜI BÁN']], 'detail' => [['id' => 'table', 'type' => 'table', 'dataSource' => 'rows', 'tableType' => 'dynamic']], 'footer' => []]; }
    public function html(): string { $h=''; foreach($this->labels() as $label){$h.='<th>'.$label.'</th>';} $c=''; foreach($this->fields() as $f){$binding = $f === 'OccupancyRate' ? '{{row.OccupancyRate}}%' : '{{row.'.$f.($f!=='SalesPersonCode'&&$f!=='SalesPersonName'?'|number':'').'}}'; $c.='<td>'.$binding.'</td>';} return '<div class="report-header"><div>{{hotel.logo}}</div><div class="hotel-information">Địa chỉ: {{hotel.address}}<br>Người dùng: {{report.generated_by}}<br>Ngày: {{report.generated_at}}</div></div><h1>BÁO CÁO DOANH THU THEO NGƯỜI BÁN</h1><p class="period">Ngày: {{parameters.p_from_date}} ~ {{parameters.p_to_date}}</p><table><thead><tr>'.$h.'</tr></thead><tbody><tr class="pms-detail-row" data-source="rows">'.$c.'</tr><tr class="total"><td colspan="2">Tổng: {{aggregate.rows.count}}</td><td></td><td>{{aggregate.rows.sum.RoomNights|number}}</td><td>{{aggregate.rows.sum.GuestQty|number}}</td><td colspan="2"></td><td>{{aggregate.rows.sum.RoomRevenue|number}}</td><td>{{aggregate.rows.sum.FbRevenue|number}}</td><td>{{aggregate.rows.sum.OtherRevenue|number}}</td><td>{{aggregate.rows.sum.TotalRevenue|number}}</td></tr></tbody></table>'; }
    public function css(): string { return '.report-header{display:flex;justify-content:space-between;min-height:50px}.hotel-information{text-align:right;font-size:9px;line-height:1.5}h1{text-align:center;font-size:16px;margin:8px 0 3px}p.period{text-align:center;font-style:italic;font-size:9px}table{width:100%;border-collapse:collapse;font-size:8px}th,td{border:1px solid #aeb5c0;padding:3px 2px}th{background:#d9deea;text-align:center}.total td{background:#d9deea;font-weight:bold}'; }
};
